r"""Generates facegen_age.h from the game's FaceGen statistical model.

The age (in years) and gender (-1 male .. +1 female) of a face are linear
functions over the FaceGen coefficient spaces: value = dot(coeffs, vector) +
offset, computed separately in the symmetric-geometry (GS, 50 floats) and
symmetric-texture (TS, 50 floats) subspaces (FaceGen SDK "offset linear
controls"). The vectors/offsets live in `facegen\si.ctl` (magic FRCTL001)
inside `Fallout - Misc.bsa`; all five race groups in the shipped file are
byte-identical, so the "All" group is used.

Usage:  python gen_facegen_age.py <path-to-si.ctl> > ..\facegen_age.h
(Extract si.ctl from the BSA first; any BSA tool works.)
"""
import struct, sys

data = open(sys.argv[1], "rb").read()
assert data[:8] == b"FRCTL001", data[:8]
pos = 8 + 8  # magic + geometry/texture basis versions
GS, GA, TS, TA = struct.unpack_from("<IIII", data, pos)
pos += 16
assert (GS, GA, TS, TA) == (50, 30, 50, 0), (GS, GA, TS, TA)

# Skip the four labeled linear-control sections.
for size in (GS, GA, TS, TA):
    (count,) = struct.unpack_from("<I", data, pos)
    pos += 4
    for _ in range(count):
        pos += 4 * size
        (n,) = struct.unpack_from("<I", data, pos)
        pos += 4 + n

# Offset linear controls, per race group (All, Afro, Asia, Eind, Euro):
# [ageGS(50), ageGSoff, ageTS(50), ageTSoff,
#  genderGS(50), genderGSoff, genderTS(50), genderTSoff]
def block(n):
    global pos
    v = struct.unpack_from(f"<{n}f", data, pos)
    pos += 4 * n
    return v

age_gs, age_gs_off = block(GS), block(1)[0]
age_ts, age_ts_off = block(TS), block(1)[0]
gen_gs, gen_gs_off = block(GS), block(1)[0]
gen_ts, gen_ts_off = block(TS), block(1)[0]

def emit(name, vec):
    rows = [", ".join(f"{v:.9g}f" for v in vec[i : i + 5]) for i in range(0, len(vec), 5)]
    body = ",\n    ".join(rows)
    print(f"constexpr float {name}[{len(vec)}] = {{\n    {body},\n}};")

print("// Generated by tools/gen_facegen_age.py from facegen\\si.ctl")
print("// (Fallout - Misc.bsa, magic FRCTL001, 'All' race group). Do not hand-edit.")
print("//")
print("// value = dot(coeffs, vector) + offset, separately in the GS and TS")
print("// subspaces; age is in years, gender is -1 (male) .. +1 (female).")
print("#pragma once")
print()
print("namespace facegen_age")
print("{")
print()
print("constexpr int kCoefficientCount = 50;")
print()
emit("kAgeGs", age_gs)
print(f"constexpr float kAgeGsOffset = {age_gs_off:.9g}f;")
print()
emit("kAgeTs", age_ts)
print(f"constexpr float kAgeTsOffset = {age_ts_off:.9g}f;")
print()
emit("kGenderGs", gen_gs)
print(f"constexpr float kGenderGsOffset = {gen_gs_off:.9g}f;")
print()
emit("kGenderTs", gen_ts)
print(f"constexpr float kGenderTsOffset = {gen_ts_off:.9g}f;")
print()
print("} // namespace facegen_age")
